<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="fonts/Roboto-Light.ttf">
    <link rel="stylesheet" href="fonts/Roboto-Regular.ttf">
    <link rel="stylesheet" href="fonts/Roboto-Black.ttf">
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/style.css">
    <title>Home | Your place</title>
</head>
<body>

<div class="rooms_types" id="rooms">
</div>

<!--results page-->
<div class="rooms_results">
    <div class="single_room room_card">
        <div class="description">
            <p><img src="./img/delete.svg">Description</p>
            <p class="text">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae aliquet lorem. Nulla nisi libero, molestie id hendrerit nec, mollis mattis augue. Nunc facilisis in est eu placerat. Ut cursus viverra dui et suscipit. Maecenas lacinia sed diam eu rhoncus. In a aliquet sem. Nunc lorem enim, maximus eu convallis vel, euismod ac dui.</p>
            <p>Minimum stay: <span id="single_stay">3</span> night</p>
        </div>
        <div class="room_img">
            <img src="./img/rooms/single_bed.jpg" alt="Single room photo">
        </div>

        <div class="room_details">
            <h4>Price for 3 nights</h4>
            <h2>£ <span id="single_price">57</span></h2>
            <h3>
                <h3>Single Room</h3>
                <img src="img/person.png" alt="person" class="person">
            </h3>
            <p class="more_info">More about the room</p>
            </div>
    </div>
    <div class="single_room room_card">
        <div class="description">
            <p><img src="./img/delete.svg">Description</p>
            <p class="text">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae aliquet lorem. Nulla nisi libero, molestie id hendrerit nec, mollis mattis augue. Nunc facilisis in est eu placerat. Ut cursus viverra dui et suscipit. Maecenas lacinia sed diam eu rhoncus. In a aliquet sem. Nunc lorem enim, maximus eu convallis vel, euismod ac dui.</p>
            <p>Minimum stay: <span id="single_stay">3</span> night</p>
        </div>
        <div class="room_img">
            <img src="./img/rooms/double_room.jpg" alt="Double room photo">
        </div>
        <div class="room_details">
            <h4>Price for 3 nights</h4>
            <h2>£ <span id="double_price">57</span></h2>
            <h3>
                <h3>Double Room</h3>
                <img src="img/person.png" alt="person" class="person">
                <img src="img/person.png" alt="person" class="person">
                <img src="img/baby.png" alt="baby" class="person">
            </h3>
            <p class="more_info">More about the room</p>
        </div>
    </div>
    <div class="single_room room_card">
        <div class="description">
            <p><img src="./img/delete.svg">Description</p>
            <p class="text">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae aliquet lorem. Nulla nisi libero, molestie id hendrerit nec, mollis mattis augue. Nunc facilisis in est eu placerat. Ut cursus viverra dui et suscipit. Maecenas lacinia sed diam eu rhoncus. In a aliquet sem. Nunc lorem enim, maximus eu convallis vel, euismod ac dui.</p>
            <p>Minimum stay: <span id="single_stay">3</span> night</p>
        </div>
        <div class="room_img">
            <img src="./img/rooms/vip_bed.jpg" alt="Single room photo">
        </div>
        <div class="room_details">

            <h4>Price for 3 nights</h4>
            <h2>£ <span id="lux_price">5700</span></h2>
            <h3>VIP Room</h3>
            <h3><img src="img/person.png" alt="person" class="person"> x 10</h3>
            <p class="more_info">More about the room</p>
        </div>
    </div>
    
</body>
<script src="js/jquery-1.12.4.js"></script>
<script src="js/jquery-ui.min.js"></script>
<script src="js/datePicker.js"></script>
<script src="js/handlebars-v4.0.11.js"></script>
<script src="js/ajax_request.js"></script>
<script src="js/main.js" defer></script>
</html>