<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="fonts/Roboto-Light.ttf">
    <link rel="stylesheet" href="fonts/Roboto-Regular.ttf">
    <link rel="stylesheet" href="fonts/Roboto-Black.ttf">
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/style.css">
    <title>Home | Your place</title>
</head>
<body>
<div class="rooms_types" id="rooms">
</div>
</body>
<script src="js/jquery-1.12.4.js"></script>
<script src="js/jquery-ui.min.js"></script>
<script src="js/handlebars-v4.0.11.js"></script>
<script src="js/ajax_request.js"></script>
<script src="js/main.js" defer></script>
</html>