<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="fonts/Roboto-Light.ttf">
    <link rel="stylesheet" href="fonts/Roboto-Regular.ttf">
    <link rel="stylesheet" href="fonts/Roboto-Black.ttf">
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/style.css">
    <title>Home | Your place</title>
</head>
<body>
<div class="error">
    <div class="error_message">
        <p>Minimum stay is 1 nights</p>
    </div>
</div>
<div class="main">
    <div class="logo">
        <a href="/">
            <img src="./img/logo_4.png" alt="Awesome Badger logo">
        </a>
        <h1>Awesome badger bookings</h1>
    </div>
    <div class="date_range_picker">
        <form action="/" method="GET">
            <div class="form_content">
                <input type="text" id="from" name="from" placeholder="From...">
                <input type="text" id="to" name="to" placeholder="To...">
                <input type="submit" class="date_submit" value="Search">
            </div>
        </form>
        <div class="rooms_results"></div>
    </div>

    <div class="scroll">
        <p>take a look</p>
        <div class="scroll_arrow">
            <a href="#rooms" id="scroll_action"><img src="./img/bottom.png" alt="scroll arrow"></a>
        </div>
    </div>
</div>
<div class="rooms_types" id="rooms"></div>
</body>
<script src="js/jquery-1.12.4.js"></script>
<script src="js/jquery-ui.min.js"></script>
<script src="js/datePicker.js"></script>
<script src="js/handlebars-v4.0.11.js"></script>
<script src="js/ajax_request.js"></script>
<script src="js/roomHandlebars.js"></script>
<script src="js/resultsHandlebars.js"></script>
<script src="js/main.js" defer></script>
</html>